### ISSUE TITLE
Monitor "Help" page error

### ISSUE THREAD

**Issue by Detrua** [RaidMax/IW4M-Admin#192] opened 2021-03-27 11:16 UTC
When i try to open the Page for Help it always show up:

Sorry!
Something happened when creating this page
Problem ID - Sequence contains no matching element

**Comment by RaidMax** [comment] 2021-03-27 14:01
What version are you running? Do you have any 3rd party plugins installed?

**Comment by Detrua** [comment] 2021-04-05 21:00
Im running now on the latest version. I've added 1 Plugin.

**Comment by RaidMax** [comment] 2021-04-05 21:52
> Im running now on the latest version. I've added 1 Plugin.

can you provide the actual version number and the name of the plugin thanks

**Comment by LelieL91** [comment] 2021-04-30 12:32
As I mentioned on discord, I having the same issue on 1 of the 2 IW4MAdmin instances that I'm running.
The bugged instance is running on v2021.4.18.1 and it loads 3 plugins from the store: YADB, ping limiter, vote manager and generic log parser (last one installed but not used).
I didn't change anything in the configuration during the time, except moving from local plugins to store plugins, and I always updated IW4MAdmin at the latest version on this instance.
I'm going to wait the next release with the s1x edits, and I will try to make a clean installation but using the same mysql db.
I hope this problem is not related to the database.

**Comment by RaidMax** [comment] 2021-04-30 13:46
No it’s not related to the database, it’s related to a loaded plugin. I would need to know which third party plugin is causing it so I can harden some of the logic around dynamically loaded commands

**Comment by LelieL91** [comment] 2021-05-02 11:56
The help page problem was fixed on v2021.4.30.2, so the issue is solved on my side.

**Comment by RaidMax** [comment] 2021-05-02 20:37
Resolved in 96385e5

**Closed by RaidMax** 2021-05-02 20:37 UTC
