### ISSUE TITLE
Add the option to kick player from the webfront

### ISSUE THREAD

**Issue by Smech99** [RaidMax/IW4M-Admin#124] opened 2020-04-17 16:18 UTC
With T6 being kind of buggy with banning people from the webfront not always working properly. The ability to be able to also kick players from the webfront would be useful as currently if your ban fails to go through properly to the T6 server, you then have to the join the server and type !kick <player> <reason> and then the ban actually goes through.

**Comment by Jawesome99** [comment] 2020-04-17 16:34
![](https://puu.sh/FyO74/8b2773fbc3.png)
![](https://puu.sh/FyO7t/570a4c0787.png)

**Comment by Smech99** [comment] 2020-04-17 16:36
Oh yeah, my bad.

**Comment by ChaseHall** [comment] 2020-08-06 13:16
Kicking is added to the Webfront now, paging @Smech99 / @RaidMax to close this issue.

**Comment by RaidMax** [comment] 2020-08-06 13:39
Duplicate of https://github.com/RaidMax/IW4M-Admin/issues/142 implemented

**Closed by RaidMax** 2020-08-06 13:39 UTC
