### ISSUE TITLE
Handle plutonium reconnect

### ISSUE THREAD

**Issue by mxve** [RaidMax/IW4M-Admin#230] opened 2022-02-05 23:32 UTC
In a recent update plutonium fixed/implemented map fastdl (on iw5, t6 planned afaik), on map rotation users are forced to reconnect to the server.
IW4MAdmin is tracking the reconnects as users leaving and joining again.

Would be nice to either detect if its a reconnect requested by the server or delay the user disconnected tracking (maybe only if many people left? idk)

**Comment by RaidMax** [comment] 2022-02-06 01:02
Please provide the game log when the map rotates. I will need to use that as reference for a mitigation strategy.

**Comment by mxve** [comment] 2022-02-06 01:59
```
  1:28 J;01100001000e87bb;0;mxve
  1:43 ExitLevel: executed
  1:43 ------------------------------------------------------------
  1:43 ------------------------------------------------------------
  1:43 InitGame
  1:50 J;01100001000e87bb;0;mxve
  2:33 Q;01100001000e87bb;0;mxve
  3:12 J;01100001000e87bb;0;mxve
  3:24 say;01100001000e87bb;0;mxve;!mr
  3:29 ExitLevel: executed
  3:29 ------------------------------------------------------------
  3:29 ------------------------------------------------------------
  3:29 InitGame
  3:38 J;01100001000e87bb;0;mxve
  3:43 say;01100001000e87bb;0;mxve;!mr
  3:48 ExitLevel: executed
  3:48 ------------------------------------------------------------
  3:48 ------------------------------------------------------------
  3:48 InitGame
  3:56 J;01100001000e87bb;0;mxve
  4:30 Q;01100001000e87bb;0;mxve
```

**Comment by RaidMax** [comment] 2022-02-16 23:33
I cannot reproduce this. Running pluto iw5 r2801. I have tried map rotate to several maps and map restart and fast restart. None of them detect a disconnect. Is this something that's still occuring?

**Comment by mxve** [comment] 2022-02-17 01:17
This only happens with custom usermaps, not default maps. And it could be possible that it only happens on map_rotate, as it doesn't load a "new" map on map_restart.
I know from RektInator that the servers basically tells the user to reconnect if a custom map is loaded.
If you are connected as a client you will experience this as being thrown to the main menu and then seeing a "Reconnecting" dialog while you are getting reconnected to the server.

I've added you on Discord in case you need a fastdl or maps in general for testing.

**Comment by RaidMax** [comment] 2022-02-17 04:08
I’ll close this for now but feel free to reopen if you’re able to reproduce.

**Closed by RaidMax** 2022-02-17 04:08 UTC
